"""Persisted split assignments — the guarantee ``assign_splits`` alone cannot make.

``assign_splits`` (see :mod:`marinedata.scan`) is a pure, stateless allocator: every
call re-sorts *every* group by ``(-count, seeded_hash)`` and re-packs them against the
target ratios. That is correct and deterministic for one fixed corpus, but a corpus is
not fixed — new samples land in existing groups and brand-new groups appear over time.
When a growing group's count crosses another group's count in that sort order, its
assigned split can flip on a later run even at the same seed, and the flip can cascade
into a second group taking the vacated slot. Stability was true "so far", not guaranteed.

``registry/SPLIT_MAP.json`` turns that into a guarantee by recording every assignment
ever made. The rule is append-only: a key, once written, keeps its value for the life
of the file. A group already in the map is never re-offered to the allocator — only
groups absent from the map are assigned, against the quota the persisted groups already
used, and the result is appended. This is the "raise, don't warn" contract the rest of
the gate uses: a call that cannot honour the append-only guarantee raises rather than
silently reinterpreting or overwriting a stale map.

The map is keyed by :func:`marinedata.scan.group_key`'s output alone — it carries no
task id — so a group lands in the same split under every task that scans it.
"""

from __future__ import annotations

import json
from collections import Counter
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from .scan import SplitName, assign_splits
from .strata import DEFAULT_MIN_GROUPS, assign_splits_stratified

SCHEMA_VERSION = 1

Row = tuple[str, str, str | None]
"""``(image_sha256, split_group, stratum)`` — one row per (image, source) pair. See
:func:`rows_to_counts`."""


class SplitMapError(ValueError):
    """A SPLIT_MAP.json read or write would violate the append-only contract."""


def rows_to_counts(
    rows: Iterable[Row], *, stratified: bool = False
) -> tuple[dict[str, int], dict[str, dict[str, int]] | None]:
    """Reduce ``(image_sha256, split_group, stratum)`` rows to per-group counts.

    One count per unique image: the same physical image staged under two admitted
    sources shares one ``split_group`` (the registry's cross-source dedup rule) but
    must not be counted twice toward that group's overall size. ``stratum`` still gets
    the row once per source it was staged under, though — a cross-source duplicate is
    real evidence for *both* strata's quotas, only the overall pool must not double it.

    Shared by ``splitmap generate --in <file>`` (:mod:`marinedata.cli_splitmap`) and the
    release enumerator (:func:`marinedata.release.enumerate_release_rows`) so a
    hand-built TSV and a live staged-tree scan reduce identically.

    Raises if the same image resolves to two different groups — the registry's
    per-source ``split_group`` rule is supposed to make duplicates converge, and a
    disagreement here means that rule (or the input) is wrong, not something to
    silently pick a winner for.
    """
    group_of: dict[str, str] = {}
    members: dict[str, set[str]] = {}
    for sha256, group, stratum in rows:
        if not sha256 or not group:
            raise ValueError("row with an empty image_sha256 or split_group")
        prior = group_of.get(sha256)
        if prior is not None and prior != group:
            raise ValueError(
                f"image {sha256} maps to two different split_group values "
                f"({prior!r} and {group!r}) — split_group must be immutable per image"
            )
        group_of[sha256] = group
        if stratified:
            if not stratum:
                raise ValueError("--stratify needs a non-empty stratum on every row")
            members.setdefault(stratum, set()).add(sha256)
    counts = dict(Counter(group_of.values()))
    if not stratified:
        return counts, None
    strata = {name: dict(Counter(group_of[sha] for sha in shas)) for name, shas in members.items()}
    return counts, strata


@dataclass(frozen=True)
class SplitMap:
    """The on-disk assignment registry: what generated it, and what it has decided."""

    by: str
    seed: int
    ratios: dict[SplitName, float]
    assignments: dict[str, SplitName] = field(default_factory=dict)
    generated_at: str = ""
    release: str = ""
    """The release id ``splitmap generate --release`` was run for, kept for the life of
    the file — a map is never regenerated by a later release under a new id, so this is
    written once and never checked for a match the way ``by``/``seed``/``ratios`` are."""
    stratify: str = ""
    """What the map was stratified by (e.g. ``"source"``), or ``""`` for one pool. See
    :mod:`marinedata.strata`. Written only when set, so unstratified maps keep their
    exact bytes; checked like ``by``/``seed``/``ratios`` whenever a call allocates."""
    schema_version: int = SCHEMA_VERSION


def load_split_map(path: str | Path) -> SplitMap | None:
    """Read a SPLIT_MAP.json, or ``None`` if it does not exist yet.

    A missing file is the expected, ordinary state for a brand-new registry — it is not
    an error. A file that exists but carries an unrecognised schema version is.
    """
    p = Path(path)
    if not p.exists():
        return None
    raw = json.loads(p.read_text())
    version = raw.get("schema_version")
    if version != SCHEMA_VERSION:
        raise SplitMapError(
            f"{p} has schema_version={version!r}, this code understands "
            f"{SCHEMA_VERSION!r} — migrate the file before extending it."
        )
    return SplitMap(
        by=raw["by"],
        seed=raw["seed"],
        ratios=dict(raw["ratios"]),
        assignments=dict(raw["assignments"]),
        generated_at=raw.get("generated_at", ""),
        release=raw.get("release", ""),
        stratify=raw.get("stratify", ""),
        schema_version=version,
    )


def save_split_map(path: str | Path, split_map: SplitMap) -> None:
    """Write a SPLIT_MAP.json with a stable key order and a trailing newline.

    Field order matches the documented format; ``ratios`` and ``assignments`` are
    written with sorted keys so two runs over the same input are byte-identical.
    """
    payload = {
        "schema_version": split_map.schema_version,
        "by": split_map.by,
        "seed": split_map.seed,
        "ratios": dict(sorted(split_map.ratios.items())),
        "generated_at": split_map.generated_at,
        "release": split_map.release,
        **({"stratify": split_map.stratify} if split_map.stratify else {}),
        "assignments": dict(sorted(split_map.assignments.items())),
    }
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(payload, indent=2) + "\n")


def resolve_splits(
    path: str | Path,
    counts: dict[str, int],
    ratios: dict[SplitName, float],
    *,
    seed: int = 0,
    by: str = "site",
    now: str | None = None,
    frozen: bool = False,
    release: str | None = None,
    strata: Mapping[str, Mapping[str, int]] | None = None,
    stratify: str = "",
    min_groups: int = DEFAULT_MIN_GROUPS,
) -> dict[str, SplitName]:
    """Assign every group in ``counts`` a split, persisting the result at ``path``.

    A group already recorded in the map at ``path`` keeps its recorded split
    unconditionally, however ``counts`` has changed for it — that is the append-only
    guarantee, and it applies whichever task's scan produced ``counts``, since the map
    is keyed by group only. Groups absent from the map are assigned by
    :func:`~marinedata.scan.assign_splits` against the quota remaining once the
    persisted groups' current contribution is counted, then appended and written back.

    With no file yet at ``path``, this reproduces exactly what
    ``assign_splits(counts, ratios, seed=seed)`` would return — persistence changes
    nothing about a first run over a fresh corpus.

    Raises ``SplitMapError`` if a map already exists at ``path`` with a different
    ``by``, ``seed``, or ``ratios`` — extending a stale map under different parameters
    would silently reinterpret it rather than fail loudly.

    ``frozen=True`` is the release-build contract: every group in ``counts`` must
    already be recorded at ``path``. A group that is not raises ``SplitMapError``
    instead of being allocated and appended — a frozen build touches nothing on disk,
    successful or not, so a release can never quietly grow the shared map that other
    tasks depend on.

    ``release``: recorded on the map the first time it is written (``existing is
    None``) — ``marinedata splitmap generate --release <id>`` passes this through so the
    map records which release it was generated for. Extending an existing map never
    overwrites it with a different value; it is not part of the ``by``/``seed``/
    ``ratios`` mismatch check above, since a shared map legitimately outlives the one
    release that first created it.

    ``strata`` + ``stratify``: allocate new groups per stratum (see
    :mod:`marinedata.strata`) instead of against one pool. ``strata`` maps stratum ->
    group -> images and must cover exactly the groups in ``counts``; ``stratify`` names
    what the strata are and is recorded on the map. A non-frozen call whose
    ``stratify`` differs from the map's raises, like a ``by``/``seed``/``ratios``
    mismatch; a frozen call allocates nothing, so it does not need the strata.
    """
    if (strata is None) != (not stratify):
        raise SplitMapError("pass `strata` and `stratify` together, or neither")
    if strata is not None:
        covered = {key for groups in strata.values() for key in groups}
        if covered != set(counts):
            raise SplitMapError(
                f"strata cover {len(covered)} groups but counts has {len(counts)} — "
                "every group must belong to at least one stratum and no stratum may "
                "name a group absent from counts"
            )
    existing = load_split_map(path)
    if existing is not None:
        if existing.by != by or existing.seed != seed or existing.ratios != dict(ratios):
            raise SplitMapError(
                f"{path} was generated with by={existing.by!r} seed={existing.seed} "
                f"ratios={existing.ratios} — this call used by={by!r} seed={seed} "
                f"ratios={dict(ratios)}. A mismatched call cannot safely extend a stale "
                "map: use the same parameters, or start a new map deliberately."
            )
        if not frozen and existing.stratify != stratify:
            raise SplitMapError(
                f"{path} was generated with stratify={existing.stratify!r} — this call "
                f"used stratify={stratify!r}. Extending it that way would allocate new "
                "groups against a different quota than the one it was built with."
            )
        persisted = dict(existing.assignments)
        generated_at = existing.generated_at
        release_value = existing.release
    else:
        if frozen:
            raise SplitMapError(
                f"{path} does not exist — a frozen build requires a split map already "
                "generated (see `marinedata splitmap generate`)."
            )
        persisted = {}
        generated_at = now if now is not None else datetime.now(UTC).isoformat()
        release_value = release or ""

    new_counts = {key: count for key, count in counts.items() if key not in persisted}

    if frozen and new_counts:
        missing = ", ".join(sorted(new_counts))
        raise SplitMapError(
            f"{path} is frozen: group(s) not in the map: {missing}. A frozen build "
            "never allocates or appends — regenerate the map to include them first."
        )

    new_assignment: dict[str, SplitName] = {}
    if new_counts and strata is not None:
        new_assignment = assign_splits_stratified(
            strata,
            ratios,
            seed=seed,
            pinned={key: persisted[key] for key in counts if key in persisted},
            min_groups=min_groups,
        )
    elif new_counts:
        total = sum(counts.values())
        filled = dict.fromkeys(ratios, 0)
        for key, split in persisted.items():
            if key in counts:
                filled[split] = filled.get(split, 0) + counts[key]
        new_assignment = assign_splits(new_counts, ratios, seed=seed, total=total, filled=filled)

    merged = {**persisted, **new_assignment}

    # Structurally unreachable given the split above (persisted keys never reach
    # `assign_splits`), kept as the explicit "raise, don't warn" guard the append-only
    # contract promises rather than relying on that invariant holding silently forever.
    for key, split in persisted.items():
        if merged[key] != split:
            raise SplitMapError(
                f"append-only violation: group {key!r} would move from {split!r} to {merged[key]!r}"
            )

    if not frozen and (new_assignment or existing is None):
        save_split_map(
            path,
            SplitMap(
                by=by,
                seed=seed,
                ratios=dict(ratios),
                assignments=merged,
                generated_at=generated_at,
                release=release_value,
                stratify=stratify,
            ),
        )

    return {key: merged[key] for key in counts}
