"""WP-7d (D-S2): generate registry/crosswalks/coralnet-label-id.yaml.

    python scripts/coralnet_label_id_codegen.py <repo_root>

One curated edge per CoralNet label id that one of our CoralNet-family sources uses. The id
evidence is already committed in each source's vocab TSV description column:
``reefolution`` ("CoralNet <id> <name> (<group>)", from its labelset.csv) and
``noaa-benthic-t3`` ("... | coralnet:<id>", from the NOAA class list). The target is the
source's own audited crosswalk edge for that code; names and groups come from the public
label table (registry/taxonomy/coralnet-labels-*.parquet). Two sources that disagree on
one id is a hard error: the id means one thing.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
sys.path.insert(0, str(ROOT / "src"))
from marinedata.coralnet_labels import load_table  # noqa: E402

ID_IN_DESC = {
    "reefolution": ("reefolution", re.compile(r"^CoralNet (\d+) ")),
    "noaa-benthic-t3": ("coralnet-noaa-pifsc", re.compile(r"coralnet:(\d+)")),
}


# Where the source crosswalk left an id unmappable only because its generator had no rule
# ("NO RULE for ..."), the id-level edge states the coarsest true node instead (WP-7d,
# model-audited in docs/taxonomy-audit-2026-09-25.tsv). The source crosswalk is unchanged.
OVERRIDES = {
    1262: ({"taxon": "HC", "form": "CB"}, "coarsened", "branching hard coral, genus not given"),
    1266: (
        {"taxon": "HC"},
        "coarsened",
        "columnar hard coral; RS-Benthic has no columnar form node, so form is left unsupervised",
    ),
    1318: (
        {"taxon": "CLAM"},
        "coarsened",
        "giant clam (Tridacninae) is inside the CLAM node (Bivalvia, alias tridacna)",
    ),
    1321: (
        {"taxon": "BIOTIC"},
        "coarsened",
        "unclassified sessile invertebrate: only 'a living thing' is certain "
        "(sponge, cnidarian or other)",
    ),
    3507: (
        {"taxon": "CNIDARIA"},
        "coarsened",
        "wire and black coral = Antipatharia; no node below Cnidaria covers it",
    ),
    7011: (
        {"taxon": "DC"},
        "coarsened",
        "COTS predation scar = recently dead coral skeleton; the cause (Acanthaster) is lost",
    ),
}


def _edges(crosswalk_id: str) -> dict[str, dict]:
    for path in (ROOT / "registry/crosswalks").glob("*.yaml"):
        for cw in yaml.safe_load(path.read_text()).get("crosswalks", []):
            if cw["id"] == crosswalk_id:
                return {e["source_label"]: e for e in cw["edges"]}
    raise SystemExit(f"crosswalk {crosswalk_id} not found")


def main() -> None:
    table = load_table(ROOT / "registry")
    by_id: dict[int, dict] = {}
    for source, (xw, pattern) in ID_IN_DESC.items():
        edges = _edges(xw)
        tsv = ROOT / f"registry/taxonomy/vocab/{source}.tsv"
        for line in tsv.read_text().splitlines():
            if line.startswith(("#", "label\t")) or not line:
                continue
            code, count, desc = ([*line.split("\t"), "", ""])[:3]
            m = pattern.search(desc)
            if not m:
                continue
            lid, edge = int(m.group(1)), edges[code]
            new = {k: edge[k] for k in ("targets", "fidelity") if k in edge}
            seen = by_id.setdefault(lid, {"edge": new, "uses": []})
            if seen["edge"] != new:
                raise SystemExit(f"CoralNet {lid}: {source}:{code} {new} != {seen}")
            seen["uses"].append(f"{source}:{code} ({count or '?'})")
    for lid, (targets, fidelity, why) in OVERRIDES.items():
        if by_id[lid]["edge"].get("fidelity") != "unmappable":
            raise SystemExit(f"override {lid}: the source edge is no longer unmappable")
        by_id[lid]["edge"] = {"targets": targets, "fidelity": fidelity}
        by_id[lid]["uses"].append(f"WP-7d override of an unmappable source edge: {why}")
    lines = [
        "# GENERATED by scripts/coralnet_label_id_codegen.py (WP-7d, D-S2) - "
        "rerun, do not hand-edit.",
        "# Keys are CoralNet's global label ids (https://coralnet.ucsd.edu/label/<id>/). Each edge",
        "# carries the target already audited in the source crosswalk that uses the id; the note",
        "# gives the public label's name and functional group and every source code behind it.",
        "# An id with no edge here still resolves: "
        "marinedata.coralnet_labels.CoralNetLabelIdResolver",
        "# falls back to its functional group through `coralnet-labelset` (coarsened at best).",
        "crosswalks:",
        "  - id: coralnet-label-id",
        "    source_schema: coralnet-label-id",
        "    target_schema: rs-benthic-v1",
        "    description: CoralNet global label ids onto RS-Benthic v1 "
        "(curated edges; functional-group fallback in code).",
        "    edges:",
    ]
    for lid in sorted(by_id):
        row, e = table.get(lid, {}), by_id[lid]["edge"]
        note = (
            f"CoralNet {lid} {row.get('name', '?')} ({row.get('functional_group', '?')}); "
            + ", ".join(by_id[lid]["uses"])
        )
        targets = ", ".join(f"{k}: {v}" for k, v in e.get("targets", {}).items())
        body = f'source_label: "{lid}", '
        body += f"targets: {{ {targets} }}, " if targets else ""
        body += f"fidelity: {e.get('fidelity', 'exact')}, note: {json.dumps(note)}"
        lines.append(f"      - {{ {body} }}")
    out = ROOT / "registry/crosswalks/coralnet-label-id.yaml"
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}: {len(by_id)} label ids")


if __name__ == "__main__":
    main()
